import { motion } from "framer-motion";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
  BarChart,
  Bar,
} from "recharts";
import { Zap, Calendar, Package, MinusCircle, FileText, TrendingUp, DollarSign, Download, ChevronDown } from "lucide-react";
import { useState } from "react";

import { AI_ACTIONS, RISKS } from "../data/mockData";
import ConfidenceMeter from "../components/ConfidenceMeter";

export default function AIRecommendations() {
  const [showExportMenu, setShowExportMenu] = useState(false);
  
  // Get the top priority risk for context
  const topRisk = RISKS.find(r => r.priority === "urgent");
  
  const handleExport = (format) => {
    alert(`Exporting report in ${format.toUpperCase()} format...`);
    setShowExportMenu(false);
  };
  
  const actions = [
    {
      id: "expedite",
      title: "Expedite Shipment",
      description: AI_ACTIONS[0].description,
      cost: AI_ACTIONS[0].avgCost,
      savings: AI_ACTIONS[0].avgSavings,
      probability: Math.round(AI_ACTIONS[0].successRate * 100),
      roi: AI_ACTIONS[0].avgROI,
      timeToImplement: AI_ACTIONS[0].avgTimeToImplement,
      useCases: AI_ACTIONS[0].useCases,
      icon: <Zap size={22} />,
      recommended: true,
      example: topRisk ? `Expedite ${topRisk.flightId}` : "Expedite critical flight",
    },
    {
      id: "reschedule",
      title: "Reschedule Production",
      description: AI_ACTIONS[1].description,
      cost: AI_ACTIONS[1].avgCost,
      savings: AI_ACTIONS[1].avgSavings,
      probability: Math.round(AI_ACTIONS[1].successRate * 100),
      roi: AI_ACTIONS[1].avgROI,
      timeToImplement: AI_ACTIONS[1].avgTimeToImplement,
      useCases: AI_ACTIONS[1].useCases,
      icon: <Calendar size={22} />,
      example: "Shift peak-hour jobs to off-peak",
    },
    {
      id: "pullspares",
      title: "Pull Spare Parts",
      description: AI_ACTIONS[2].description,
      cost: AI_ACTIONS[2].avgCost,
      savings: AI_ACTIONS[2].avgSavings,
      probability: Math.round(AI_ACTIONS[2].successRate * 100),
      roi: AI_ACTIONS[2].avgROI,
      timeToImplement: AI_ACTIONS[2].avgTimeToImplement,
      useCases: AI_ACTIONS[2].useCases,
      icon: <Package size={22} />,
      example: "Source from alternate facility",
    },
    {
      id: "noaction",
      title: "Monitor Only",
      description: AI_ACTIONS[3].description,
      cost: AI_ACTIONS[3].avgCost,
      savings: AI_ACTIONS[3].avgSavings,
      probability: Math.round(AI_ACTIONS[3].successRate * 100),
      roi: AI_ACTIONS[3].avgROI,
      timeToImplement: AI_ACTIONS[3].avgTimeToImplement,
      useCases: AI_ACTIONS[3].useCases,
      icon: <MinusCircle size={22} />,
      example: "Continue normal operations",
    },
  ];

  const chartData = actions.map((a) => ({
    name: a.title.split(' ')[0], // Shortened for chart
    probability: a.probability,
    cost: a.cost === "$0" ? 0 : parseInt(a.cost.split('-')[0].replace(/[^0-9]/g, "")) / 100, // normalize for chart
  }));

  return (
    <div className="min-h-screen bg-slate-950 text-white p-10 font-sans">
      {/* Header */}
      <div className="mb-10 flex items-start justify-between">
        <div className="flex-1">
          <h1 className="text-4xl font-bold text-teal-400 mb-2">
            AI-Powered Action Recommendations
          </h1>
          <p className="text-gray-400 text-lg">
            Prescriptive actions generated by Snowflake Cortex AI to optimise ROI and
            ensure On-Time-In-Full (OTIF) performance across your supply chain.
          </p>
        </div>
        {/* Export Button */}
        <div className="relative">
          <button
            onClick={() => setShowExportMenu(!showExportMenu)}
            className="flex items-center gap-2 px-4 py-2 rounded-lg glass-card border border-teal-400/50 text-teal-400 hover:bg-[#1a2f4d] transition"
          >
            <Download className="w-4 h-4" />
            <span className="text-sm font-semibold">Export Report</span>
            <ChevronDown className="w-4 h-4" />
          </button>
          {showExportMenu && (
            <div className="absolute right-0 mt-2 w-40 glass-card border border-teal-400/30 rounded-lg shadow-lg overflow-hidden z-10">
              <button
                onClick={() => handleExport('pdf')}
                className="w-full px-4 py-2 text-left text-sm hover:bg-[#1a2f4d] transition"
              >
                Export as PDF
              </button>
              <button
                onClick={() => handleExport('csv')}
                className="w-full px-4 py-2 text-left text-sm hover:bg-[#1a2f4d] transition"
              >
                Export as CSV
              </button>
              <button
                onClick={() => handleExport('json')}
                className="w-full px-4 py-2 text-left text-sm hover:bg-[#1a2f4d] transition"
              >
                Export as JSON
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Action Cards */}
      <div className="grid grid-cols-2 gap-6 mb-12">
        {actions.map((a) => (
          <motion.div
            key={a.id}
            whileHover={{ scale: 1.03 }}
            className={`rounded-2xl p-6 shadow-lg border relative
              ${
                a.recommended
                  ? "border-teal-400 bg-gradient-to-br from-[#0f223f] to-[#112b4a] shadow-[0_0_20px_#00f5d4]"
                  : "border-white/10 glass-card"
              }`}
          >
            <div className="flex items-center gap-3 mb-4">
              <span className="text-teal-400">{a.icon}</span>
              <h2 className="text-xl font-semibold">{a.title}</h2>
              {a.recommended && (
                <span className="ml-auto bg-teal-500 text-xs px-3 py-1 rounded-full text-white font-semibold">
                  ✓ AI Recommended
                </span>
              )}
            </div>
            
            <p className="text-sm text-gray-400 mb-4 italic">{a.description}</p>
            
            <div className="mb-4">
              <ConfidenceMeter confidence={a.probability / 100} size="md" />
            </div>
            
            <div className="space-y-2 mb-4">
              <div className="flex items-center gap-2">
                <DollarSign className="w-4 h-4 text-gray-400" />
                <p className="text-gray-300 text-sm">
                  Cost: <span className="text-white font-semibold">{a.cost}</span>
                </p>
              </div>
              
              <div className="flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-gray-400" />
                <p className="text-gray-300 text-sm">
                  Savings: <span className="text-green-400 font-semibold">{a.savings}</span>
                </p>
              </div>
              
              <p className="text-sm">
                Success Rate:{" "}
                <span
                  className={`font-bold ${
                    a.probability >= 80
                      ? "text-green-400"
                      : a.probability >= 60
                      ? "text-yellow-400"
                      : "text-red-400"
                  }`}
                >
                  {a.probability}%
                </span>
              </p>
              
              <p className="text-sm text-gray-400">
                ROI: <span className="text-teal-300 font-bold text-lg">{a.roi}</span>
              </p>
              
              <p className="text-xs text-gray-500">
                Implementation time: {a.timeToImplement}
              </p>
            </div>
            
            <div className="pt-4 border-t border-gray-700">
              <p className="text-xs text-gray-500 mb-2">Best for:</p>
              <div className="flex flex-wrap gap-1">
                {a.useCases.map((useCase, idx) => (
                  <span key={idx} className="text-xs bg-gray-700/50 px-2 py-1 rounded">
                    {useCase}
                  </span>
                ))}
              </div>
            </div>
            
            {a.example && (
              <div className="mt-3 pt-3 border-t border-gray-700/50">
                <p className="text-xs text-teal-400">Example: {a.example}</p>
              </div>
            )}
          </motion.div>
        ))}
      </div>

      {/* Comparison Chart */}
      <motion.div
        whileHover={{ scale: 1.01 }}
        className="glass-card rounded-2xl shadow-lg p-6 mb-12 border border-white/10"
      >
        <h2 className="text-lg font-semibold text-teal-300 mb-4">
          Action Comparison
        </h2>
        <ResponsiveContainer width="100%" height={250}>
          <BarChart data={chartData}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1f3558" />
            <XAxis dataKey="name" stroke="#aaa" />
            <YAxis stroke="#aaa" />
            <Tooltip
              contentStyle={{
                backgroundColor: "#0f223f",
                borderRadius: "10px",
              }}
            />
            <Bar dataKey="probability" fill="#00f5d4" radius={[6, 6, 0, 0]} />
            <Line
              type="monotone"
              dataKey="cost"
              stroke="#4fc3f7"
              strokeWidth={3}
            />
          </BarChart>
        </ResponsiveContainer>
      </motion.div>

      {/* AI Narrative */}
      <motion.div
        whileHover={{ scale: 1.01 }}
        className="glass-card rounded-2xl shadow-lg p-6 mb-12 border border-white/10"
      >
        <h2 className="text-lg font-semibold text-teal-300 mb-4">
          🤖 AI Analysis & Recommendation
        </h2>
        <p className="text-gray-300 leading-relaxed mb-4">
          Based on the current risk profile,{" "}
          <span className="text-teal-400 font-semibold">Expedite Shipment</span> offers
          the highest probability of success ({actions[0].probability}%) with a favorable ROI
          of {actions[0].roi} compared to other alternatives.
        </p>
        
        {topRisk && (
          <div className="bg-black/30 p-4 rounded-lg mb-4">
            <p className="text-sm font-semibold text-orange-400 mb-2">Active Critical Risk:</p>
            <p className="text-sm text-gray-300">{topRisk.cortexNarrative}</p>
            <div className="mt-3 flex gap-4 text-xs">
              <div>
                <span className="text-gray-500">Estimated Cost:</span>{" "}
                <span className="text-red-300 font-semibold">{topRisk.estimatedCost}</span>
              </div>
              <div>
                <span className="text-gray-500">Potential Savings:</span>{" "}
                <span className="text-green-300 font-semibold">{topRisk.estimatedSavings}</span>
              </div>
              <div>
                <span className="text-gray-500">ROI:</span>{" "}
                <span className="text-teal-300 font-semibold">{topRisk.roi}</span>
              </div>
            </div>
          </div>
        )}
        
        <p className="text-sm text-gray-400 leading-relaxed">
          This recommendation was derived from live flight ETA drifts, machine
          sensor data, spare parts inventory levels, production schedules, and cost trade-offs 
          modeled inside <span className="text-blue-400 font-semibold">Snowflake Cortex</span>.
          The model analyzed {RISKS.length} active risk scenarios across {Object.keys(RISKS.reduce((acc, r) => ({...acc, [r.facility]: true}), {})).length} facilities
          to generate these prescriptive actions.
        </p>
      </motion.div>
    </div>
  );
}
